apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myfirst-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vishalvrusha/argoCD.git
    targetRevision: HEAD
    path: myproject
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

