apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-argo
spec:
  selector:
    matchLabels:
      app: myapp-argo
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp-argo
    spec:
      containers:
      - name: myapp-argo
        image: vishalmv6/my_first_image:1.1
        ports:
        - containerPort: 8080
